export {default as AvatarImg} from './avatar.jpg'
export {default as hotelHeroImg} from './hotel-hero.jpg'
export {default as franceImg} from './france.jpg'
export {default as turkeyImg} from './turkey.jpg'
export {default as belairImg} from './belair.jpg'
export {default as londonImg} from './london.jpg'
export {default as nigeriaImg} from './nigeria.jpg'